INSERT INTO comentarios (contenido, usuario_id_fk, post_id_fk) VALUES
                                                                   ('Muy interesante este post', 1, 1),
                                                                   ('No estoy de acuerdo con este punto', 2, 1),
                                                                   ('Gran análisis, gracias por compartir', 3, 2),
                                                                   ('Un punto de vista muy único', 4, 3),
                                                                   ('Nunca lo había pensado de esa manera', 5, 4),
                                                                   ('Esto me ha ayudado a entender mejor el tema', 1, 5),
                                                                   ('Me gusta cómo está escrito este post', 2, 6),
                                                                   ('Estoy aprendiendo mucho con estos posts', 3, 7),
                                                                   ('¿Podrías profundizar más en este tema?', 4, 8),
                                                                   ('Excelente post, muy informativo', 5, 9),
                                                                   ('Creo que hay un error en tu argumento', 1, 10),
                                                                   ('Estoy totalmente de acuerdo', 2, 11),
                                                                   ('Me gustaría ver más contenido como este', 3, 12),
                                                                   ('No había considerado este punto de vista antes', 4, 13),
                                                                   ('Esta información es oro puro', 5, 14),
                                                                   ('Tienes un nuevo seguidor gracias a este post', 1, 15),
                                                                   ('¿Cómo investigaste para este post?', 2, 16),
                                                                   ('Este tema siempre me ha interesado', 3, 17),
                                                                   ('Finalmente alguien lo explica bien', 4, 18),
                                                                   ('Tienes que escribir un libro sobre esto', 5, 19),
                                                                   ('No es lo que esperaba, pero está bien', 1, 20),
                                                                   ('Creo que falta profundizar en algunos puntos', 2, 21),
                                                                   ('Esto abre un nuevo debate interesante', 3, 22),
                                                                   ('En desacuerdo, pero respeto tu punto de vista', 4, 23),
                                                                   ('¡Qué gran descubrimiento este post!', 5, 24),
                                                                   ('Esto es exactamente lo que necesitaba leer', 1, 25),
                                                                   ('Me encanta tu estilo de escritura', 2, 26),
                                                                   ('Esto es muy útil, gracias', 3, 27),
                                                                   ('Me quedé pensando en este tema', 4, 28),
                                                                   ('Es un enfoque muy original', 5, 29),
                                                                   ('No conocía esta información, gracias', 1, 30),
                                                                   ('Estoy impresionado con la profundidad de este post', 2, 31),
                                                                   ('Definitivamente compartiré esto', 3, 32),
                                                                   ('Hay un error en uno de tus datos', 4, 33),
                                                                   ('Tu forma de explicar es muy clara', 5, 34),
                                                                   ('Podrías hacer una serie de posts sobre esto', 1, 35),
                                                                   ('Creo que esto podría mejorar', 2, 36),
                                                                   ('Esto responde muchas de mis preguntas', 3, 37),
                                                                   ('He leído sobre esto antes, pero nunca tan bien explicado', 4, 38),
                                                                   ('Esto merece más reconocimiento', 5, 39),
                                                                   ('Estaba buscando exactamente esta información', 1, 40),
                                                                   ('Me gusta cómo conectas los puntos', 2, 41),
                                                                   ('Espero más posts como este', 3, 42),
                                                                   ('Creo que hay otras opiniones a considerar', 4, 43),
                                                                   ('Muy detallado y bien investigado', 5, 44),
                                                                   ('Podrías expandirte en este punto', 1, 45),
                                                                   ('Interesante, pero necesito más información', 2, 46),
                                                                   ('Esto cambia mi perspectiva sobre el tema', 3, 47),
                                                                   ('No estoy seguro de estar de acuerdo, pero es interesante', 4, 48),
                                                                   ('Tu análisis es muy profundo', 5, 49),
                                                                   ('¿Podrías recomendarme más lecturas sobre esto?', 1, 50),
                                                                   ('Un enfoque muy necesario para este tema', 2, 51),
                                                                   ('Nunca había considerado este aspecto', 3, 52),
                                                                   ('Esto me ha hecho reflexionar mucho', 4, 53),
                                                                   ('Es la mejor explicación que he visto hasta ahora', 5, 54),
                                                                   ('Creo que falta una perspectiva importante aquí', 1, 55),
                                                                   ('Excelente trabajo en este post', 2, 56),
                                                                   ('¿Has pensado en hacer un podcast sobre estos temas?', 3, 57),
                                                                   ('Hay algunos puntos que podrían ser más claros', 4, 58),
                                                                   ('Este contenido es muy valioso', 5, 59),
                                                                   ('Tienes un talento especial para explicar cosas complejas', 1, 60),
                                                                   ('Este tema siempre me ha resultado confuso, hasta ahora', 2, 61),
                                                                   ('Realmente aprecio tu enfoque único', 3, 62),
                                                                   ('Esto añade una nueva dimensión a mi entendimiento', 4, 63),
                                                                   ('Una joya de post, gracias por compartir', 5, 64),
                                                                   ('Me has dado mucho en qué pensar', 1, 65),
                                                                   ('Tu habilidad para sintetizar es impresionante', 2, 66),
                                                                   ('Este es uno de los mejores posts que he leído', 3, 67),
                                                                   ('Hay un par de puntos que no están claros para mí', 4, 68),
                                                                   ('Gracias por iluminar este aspecto del tema', 5, 69),
                                                                   ('Esto me ha ayudado a conectar varios conceptos', 1, 70),
                                                                   ('Aprecio la profundidad y la claridad de tu escritura', 2, 71),
                                                                   ('Estaba esperando que alguien hablara sobre esto', 3, 72),
                                                                   ('Un enfoque muy fresco y necesario', 4, 73),
                                                                   ('Gran trabajo en resaltar estos puntos clave', 5, 74),
                                                                   ('Tu post es un recurso increíblemente útil', 1, 75),
                                                                   ('Has abierto un nuevo camino de discusión aquí', 2, 76),
                                                                   ('Este artículo es un tesoro de información', 3, 77),
                                                                   ('Algunas partes son un poco confusas, pero en general, bueno', 4, 78),
                                                                   ('Este tipo de contenido hace falta en la red', 5, 79),
                                                                   ('¡Qué gran forma de presentar esta información!', 1, 80),
                                                                   ('Estoy impresionado con la calidad de tu investigación', 2, 81),
                                                                   ('Has tocado puntos que nunca había considerado', 3, 82),
                                                                   ('Hay una gran idea en este post', 4, 83),
                                                                   ('Tu enfoque para este tema es muy original', 5, 84),
                                                                   ('Este post ha aclarado muchas dudas que tenía', 1, 85),
                                                                   ('Realmente disfruté leyendo esto', 2, 86),
                                                                   ('Un análisis muy completo y bien pensado', 3, 87),
                                                                   ('Hay algunos aspectos que podrían mejorarse', 4, 88),
                                                                   ('Gracias por compartir tus conocimientos', 5, 89),
                                                                   ('Este post es una excelente referencia sobre el tema', 1, 90),
                                                                   ('Has hecho un gran trabajo simplificando un tema complejo', 2, 91),
                                                                   ('Este post me ha abierto los ojos en muchos sentidos', 3, 92),
                                                                   ('Algunos puntos necesitan más desarrollo, pero buen trabajo', 4, 93),
                                                                   ('Este es exactamente el tipo de contenido que necesitaba', 5,

                                                                    94),
                                                                   ('Impresionante cómo has abordado este tema', 1, 95),
                                                                   ('Agradezco la perspectiva única que ofreces', 2, 96),
                                                                   ('Nunca me aburro de leer tus posts', 3, 97),
                                                                   ('Hay un par de afirmaciones que requieren más evidencia', 4, 98),
                                                                   ('Es refrescante leer algo tan bien investigado', 5, 99),
                                                                   ('Tu capacidad para desglosar conceptos complejos es notable', 1, 100);
