INSERT INTO Lectores (Lector_ID, Nombre) VALUES
(1, 'Ana García'),
(2, 'Carlos Pérez'),
(3, 'Luisa Fernández'),
(4, 'Jorge Martínez'),
(5, 'María Rodríguez'),
(6, 'José López'),
(7, 'Lucía González'),
(8, 'David Gómez'),
(9, 'Sofía Hernández'),
(10, 'Daniel Jiménez'),
(11, 'Marta Sánchez'),
(12, 'Antonio Ruiz'),
(13, 'Laura Moreno'),
(14, 'Manuel Alonso'),
(15, 'Sandra Navarro');
